spring.data.mongodb.uri=${MONGODB_URI}
server.port=${PORT:8080}
server.address=0.0.0.0


server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration


clerk.issuer=https://adapted-molly-71.clerk.accounts.dev
clerk.jwks-url=https://adapted-molly-71.clerk.accounts.dev/.well-known/jwks.json

clerk.webhook.secret = CmEV+h3RWvMOL5dTZwB5oEae3Y3j/R5W

#file upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

razorpay.key.id={RAZORPAY_KEY_ID}
razorpay.key.secret={RAZORPAY_KEY_SECRET}




